### ISSUE TITLE
Can we translate the content to another language? 

### ISSUE THREAD

**Issue by mohamed-ali** [soulmachine/machine-learning-cheat-sheet#19]
Is it possible to add internationalization to the content and enable translating it to other languages? 
If yes, how would you restructure the folder/file hierarchy to add the content for another language?

**Comment by greathope** [comment]
@mohamed-ali All the material is copied from machine learning a probabilistic perspective, I have no idea why these guys don't note

**Comment by mohamed-ali** [comment]
@greathope I guess then we should create an issue to cite the sources where fit.

**Comment by soulmachine** [comment]
@greathope This little cheat sheet aims to be a lite and condensed manual instead of a complete book, although currently it has a lot of sentences and diagrams similar to the "machine learning a probabilistic perspective" book, this little manual has its own goal and style eventually

**Comment by mohamed-ali** [comment]
@soulmachine the issue was closed without answering it's main question about whether or not we can translate the content to anther language?

**Comment by soulmachine** [comment]
@mohamed-ali As to the folder structure, I haven't thought it through yet.For now you can fork this repo and do whatever translation you want.
